# Lab 1: Intro to Array Operations: Broadcasting, Inner/Outer Products and More 
---

## Lab Objectives

The goals for this lab are to 


- Understand Array Broadcasting. 
- How to Perform Typical Operations on Matrices.


At the end of each section there will be questions to answer. 

<span style="color:red">To receive credit for the assignment, the questions must be completed. </span>

We will include import statements for commonly used modules in the cell below. Make sure to type `shift enter` to run it.


In [2]:
import numpy as np

# shorthand for importing random module from numpy
from numpy import random as npr

---
## (1) Broadcasting and Array Operations

In the previous lab, we mentioned 1-d arrays of the form, 
$$a=\begin{bmatrix}a_0\\ a_1 \\ \vdots \\ a_{n-1} \end{bmatrix}$$

<br>
and 2d-arrays, i.e., matrices, which have the form,
$$a=\begin{bmatrix}a_{0,0} & a_{0,1} & \dots a_{0,m-1}  \\ \vdots & \dots &  \vdots \\ a_{n-1,0} & a_{0,1} & \dots a_{n-1,m-1} \end{bmatrix}$$

<br>
Linear algebra only defines addition of vectors of the same size:
<br>
$$\begin{bmatrix} 1\\ 2 \\ 3 \\ 4 \end{bmatrix} +\begin{bmatrix} 8\\ 10 \\ 12 \\ 14 \end{bmatrix} = \begin{bmatrix} 9\\ 12 \\ 15 \\ 18 \end{bmatrix}$$
<br>
and scalar multiplication:
$$\begin{bmatrix} 1\\ 2 \\ 3 \\ 4 \end{bmatrix} \times 5 = \begin{bmatrix} 5\\ 10 \\ 15 \\ 20 \end{bmatrix}$$
and regular matrix multiplication. For 2d arrays (matrices), matrix multiplication involves first checking if the number of columns of the first matrix equals the number of rows of the second. So if the first matrix has shape (m,r) the second matrix must have shape (r,n) for some number n, else multiplication is undefined. If the matrices have shapes (m,r) and (r,n), the product has shape (m,n).


But while writing code, numpy allows for operations such as
$$\begin{bmatrix} 1\\ 2 \\ 3 \\ 4 \end{bmatrix} + 5 $$
It does not mean that we have invented new operations. Rather python interprets the above
equation to mean
$$\begin{bmatrix} 1\\ 2 \\ 3 \\ 4 \end{bmatrix} + \begin{bmatrix} 5\\5\\5\\5\end{bmatrix} = \begin{bmatrix} 6\\ 7 \\ 8 \\ 9 \end{bmatrix}$$


Similary numpy interprets
$$\begin{bmatrix} 1\\ 2 \\ 3 \\ 4 \end{bmatrix} +\begin{bmatrix} 1 & 3\end{bmatrix} $$
<br>
not as an incompatible vector addtion, but as the following legitimate one:
$$\begin{bmatrix} 1&1\\ 2&2 \\ 3&3 \\ 4&4 \end{bmatrix} +\begin{bmatrix} 1 & 3\\1&3\\1&3\\1&3\end{bmatrix}$$
<br>


These "generous interpretations" built into numpy are called **broadcasting** rules. This often allows for simpler and more human readable/understandable code. The expansions are not arbitrary, and broadcasting cannot always make any two matrices compatible. Rather there are specific rules underlying broadcasting. They are:

1. Compare the number of dimensions of each array, if one array dimension is shorter append 1d dimensions on the left until they are the same length.
2. Iterate through the new shapes. 
    1. If the arrays do not match in one dimension, and one array has a one, then repeat the 1d array to match the shape, (where we duplicate the values in the added dimension.
    2. If at any point the arrays do not match in a dimension, and neither is one, then they are incompatible.

After a common shape is found (if any), operations are performed on the broadcasted new matrices.

For example, the shapes
```
 2x3x1 
 3x5
```
are compatible, and would result in  an array of 
``` 
 2x3x5
```
Let us work through this. Applying step 1, we have, 
```
2x3x1
1x3x5
```

Then step two would result in,
```
2x3x5
2x3x5
```
if added or multiplied.

On the other hand, the shapes
```
 3x4x2
 2x1
```
are not compatible.
After step 1, they would have shapes,
```
 3x4x2
 1x2x1
```
Then in step 2 part b, they would be deemed incompatible because of the middle dimension.


for a more in depth explanation see https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

Now we go over some examples;

In [34]:
## Example of Compatible shapes
a = np.array(np.arange(3)).reshape(1,3)
b = np.array(np.arange(3)).reshape(3,1)

print("a is the row vector \n", a, "\n and has shape ", a.shape,'\n')
print("b is the column vector \n", b, "\n and has shape ", b.shape,'\n')

print("a+b is not a valid matrix operation (you cannot add a row vector to a column, you can only add matrices/vectors of the same shape). But what python understands from a+b here is very different. Both a and b are broadcasted to form 3x3 matrices (can you use the rules above to verify why?). Then python adds the broadcasted matrices to give  \n", a+b, "\n and the output has shape ", (a+b).shape,'\n')
print("a*b is not matrix multiplication, but elementwise multiplication of 2 matrices of the same shape (equivalent to .* in MATLAB). It is unfortunate * is used here. But here, our a and b do not have the same shape, but they can both broadcasted to 3x3 matrices. Then, python performs elementwise multiplication on the broadcasted matrices to output \n", a*b, "\n and has shape ", (a*b).shape)

## They are compatible, here is the result of expanding them to match the new shape of (3,3) 
print("In both cases, a is boradcasted/expanded to \n", np.repeat(a,3,axis=0),'\n')
print("And b is broadcasted/expanded to \n", np.repeat(b,3,axis=1) ,'\n')

## If we wanted to multiply the row vectors:
print('This is the regular matrix multiplication between a and b, denoted by a@b, (regular multiplication of a 1x3 and a 3x1 matrix yields a product of size 1x1): \n', a@b)
print('and the regular multiplication between b and a, denoted by b@a, (a 3x1 and a 1x3 matrix multiply to yield a 3x3 product): \n', b@a)

a is the row vector 
 [[0 1 2]] 
 and has shape  (1, 3) 

b is the column vector 
 [[0]
 [1]
 [2]] 
 and has shape  (3, 1) 

a+b is not a valid matrix operation (you cannot add a row vector to a column, you can only add matrices/vectors of the same shape). But what python understands from a+b here is very different. Both a and b are broadcasted to form 3x3 matrices (can you use the rules above to verify why?). Then python adds the broadcasted matrices to give  
 [[0 1 2]
 [1 2 3]
 [2 3 4]] 
 and the output has shape  (3, 3) 

a*b is not matrix multiplication, but elementwise multiplication of 2 matrices of the same shape (equivalent to .* in MATLAB). It is unfortunate * is used here. But here, our a and b do not have the same shape, but they can both broadcasted to 3x3 matrices. Then, python performs elementwise multiplication on the broadcasted matrices to output 
 [[0 0 0]
 [0 1 2]
 [0 2 4]] 
 and has shape  (3, 3)
In both cases, a is boradcasted/expanded to 
 [[0 1 2]
 [0 1 2]
 [0 1

In [27]:
## Example of Inompatible shapes
a = np.array(np.arange(9)).reshape(3,3)
b = np.array(np.arange(4)).reshape(4,1)

print("a is \n", a, "\n and has shape ", a.shape)
print("b is \n", b, "\n and has shape ", b.shape)
print("a+b is \n", a+b, "\n and has shape ", (a+b).shape)
print("a*b is \n", a*b, "\n and has shape ", (a+b).shape)


a is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 
 and has shape  (3, 3)
b is 
 [[0]
 [1]
 [2]
 [3]] 
 and has shape  (4, 1)


ValueError: operands could not be broadcast together with shapes (3,3) (4,1) 

### Why do we care?
Why not just write `for` loops?

Broadcasting not only simplifies the code we write, it also can be much faster. Python is an interpreted language, and if we attempt to write a `for` we can end up having code take hours longer then necessary. Python , or the corresponding module, provides shortcuts to certain code that is implemented and compiled in C. Part of being an exceptional programmer is understanding how to use the *fast lanes* provided to us by the developers.
For more details see https://docs.scipy.org/doc/numpy/reference/ufuncs.html


<span style="color:red"> This is an important lesson, since as we progress through this course, this is the difference between code that finishes running in short order or takes days to completion. </span>
<br> Here is a short example illustrating this point by naively writing our own function to multiply a multidimensional array by a scalar. 

In [31]:
## multiplies any multidimensional array, a, by a scalar b
def marrsc(a,b):
    c=np.zeros(a.shape)
    for x,y in np.nditer([a,c], op_flags = [['readonly'],["readwrite"]] ): 
        y[...] = x*b
    return a

## Create arbitrary array
a = npr.rand(50,33)

## Time how long it takes to execute give function we wrote
print('With a for loop: \n')
t1= %timeit -o marrsc(a,3.)

## Time how long it takes to use broadcasting
print('\nWith broadcasting: \n')
t2= %timeit -o a*3.

## Compare the difference
print("\n Our naive for loop is ", t1.average/t2.average, " times slower than using broadcasting.")


With a for loop: 

9.94 ms ± 589 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

With broadcasting: 

7.09 µs ± 127 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

 Our naive for loop is  1403.1222679218004  times slower then using broadcasting.


## <span style="color:red"> (1) Questions</span>

0. Create a new markdown cell below and type in the answers.

1. Please write down whether the following shapes are compatible and if so what is the resulting shape.
    1. 2x3x1 and 3
    2. 1x3 and 5x1
    3. 10x10 and 5x1
    4. 2x1x4 and 1x7x4
    5. 300x300x3 and 60x1
    
2. Which operations below would be valid operations if python did not do broadcasting? Which operations below can be performed after broadcasting? Check by writing the corresponding code in a code cell below.

    1. $$\begin{bmatrix} 6\\ 9 \\ 0 \\ 7 \end{bmatrix} * \begin{bmatrix} 2 & 4\end{bmatrix} $$ <br>
    2. $$\begin{bmatrix} 1 & 3 \\ 2 & 1  \end{bmatrix} + \begin{bmatrix} 11 & 33\end{bmatrix} $$ <br>
    3. $$\begin{bmatrix} 1 & 7 \\ 2 & 9 \\ 3 & 4 \end{bmatrix} * \begin{bmatrix} 1 \\ 3  \\ 7\end{bmatrix} $$



The basic operation we want to understand is matrix multiplication. Not the funny elementwise multiplication of matrices (which is not physically relevant except while writing clean code), but regular matrix multiplication. In numpy/python, the regular matrix multiplication (for 2d arrays) is @ or matmul.

First, recall a couple of basic points about matrix multiplication from high school. We assume that we are multiplying two matrices, $A$ and $B$, where $A$ has shape $(m,r)$ and $B$ has shape $(r,n)$ (so multiplication is possible). Note that for multiplication to work the number of columns (the second element in the shape of $A$) must equal the number of rows (the first element in the shape of $B$).

We will present two ways to multiply matrices. One will be through an inner product and the other will be using an outer product of vectors. 


In [16]:
a = npr.randint(0,4,(3,2))
b = npr.randint(0,4,(2,3))

print('The product of \n',a,'\n and \n',b,'\n is \n', a@b)
print('We could also multiply them using matmul: \n',np.matmul(a,b))

c = npr.randint(0,4,(1,3))
# Uncommenting the following line will throw up an error:
# a @ c
print('a has shape (3,2), c has shape (1,3), product is not defined: ')

d = npr.randint(0,4,(3,3))

# What happens if we try d @ c? d has shape (3,3) and c has shape (1,3).
# We cannot multiply these matrices since the number of columns of the first (3) != no. of rows of second (1). 
# Here, the operator @ will NOT broadcast c in this case into a (3,3) matrix and then 
# multiply. Rather, it will simply throw an error. This is useful because 
# you have to make sure there is some operator that doesn't do things behind your back :).
# But of course, d @ c.T works (c.T is the transpose of c with shape (3,1)).

print(d @ c.T )

# Uncommenting the following error throws an error:
# print(d @ c)


The product of 
 [[3 2]
 [3 2]
 [0 3]] 
 and 
 [[0 2 2]
 [0 0 0]] 
 is 
 [[0 6 6]
 [0 6 6]
 [0 0 0]]
We could also multiply them using matmul: 
 [[0 6 6]
 [0 6 6]
 [0 0 0]]
a has shape (3,2), c has shape (1,3), product is not defined: 
[[1]
 [9]
 [0]]



## Inner products

The inner product is also known as the dot product, a term you may be more familiar with. if you have two vectors $a$ and $b$ with n coordinates each, you arrange $a$ as a row vector (i.e. with shape 1xn) and $b$ as a column vector (with shape nx1) and multiply the two:
$$
\begin{bmatrix}a_1&\ldots& a_n\end{bmatrix} 
\begin{bmatrix} b_1\\\vdots\\ b_n\end{bmatrix} 
= a_1b_1+a_2b_2 +\ldots + a_n b_n.
$$
Of course, you could arrange $b$ as the row vector and $a$ as the column, and multiply the row vector $b$ by the column vector $a$ to get the same result.
The result is a number (1x1). Recall that the inner product gives you the angle between the vectors $a$ and $b$, specifically,
$$
a \cdot b = |a||b| \cos\theta,
$$
where $|a|$ and $|b|$ are the lengths of the vectors $a$ and $b$ respectively, and $\theta$ the angle between them. The above equation applied on $a$ and $a$ would give,
$$
a \cdot a = |a|^2\cos 0 = |a|^2,
$$
so the length of a vector is just the square root of the inner product of the vector with itself. 

### Matrix multiplication via the inner product. 

Let $A$ and $B$ be two matrices with shapes $(m,r)$ and $(r,n)$ respectively. The product has shape $(m,n)$, and the 
$(i,j)$th element of the product is just the inner product between the $i'$th row of $A$ and the $j'$th column of $B$. So  
$$
A = \begin{bmatrix} --- {{\bf a}_1} --- \\ \vdots \\ ---{{\bf a}_m} ---\end{bmatrix},
$$
where the ${\bf a}_i$s are vectors, each with $r$ coordinates (because $A$ has $r$ columns), and 
$$
B = \begin{bmatrix} | & \ldots & | \\ {{\bf b}_1} &\ldots &{{\bf b}_n} \\ | &\ldots & | \end{bmatrix},
$$
where the ${\bf b}_j$s are vectors, again each with $r$ coordinates (because $B$ has $r$ rows).
Then the product has shape $(m,n)$ (i.e. $m$ rows and $n$ columns) and its entry in the $i$th row and $j$th column is the
inner product between ${\bf a}_i$ and ${\bf b}_j$ as described above.



In [30]:
a = npr.randint(-2,2,(1,4))
b = npr.randint(-2,2,(1,4))

# Calling the dot/inner product on two row vectors throws up an error. Uncommenting the 
# following line will result in an error.
# np.dot(a,b)

# However, if u and v are not 2d arrays like above, but 1d arrays as follows:
u = npr.randint(-2,2,4)
print('u is a vector with shape ',u.shape)
v = npr.randint(-2,2,4)
print('v is a vector with shape ',v.shape)
# Then numpy.dot has no problem with aligning the vectors appropriately and giving the inner product:
print('The inner product of ',u,' and ',v,' is ',np.dot(u,v))
# The above is especially useful when we take 1-d slices of matrices, since these are returned as vectors.

# For the dot/inner product, we must arrange a as a row and b as a column. Lucky
# for us, a is already a row. So we just need to rearrange
# b.

b.shape = (4,1)

# You can now use the numpy.dot operation (or a simple @ because the inner product is just
# a special case of regular matrix multiplication. We use np.dot to emphasize we are dealing
# with vectors and we are taking the inner product. Verify this by hand.

print('The inner product of \n',a,'\n and \n',b,'\n is ',np.dot(a,b),'\n which we could also obtain using using @: ', a@b)

A = npr.randint(-3,3,(3,2))
B = npr.randint(-3,3,(2,5))


print('The product of \n',A,'\n and \n',B,'\n is \n',A @ B,'\n with shape ',(A @ B).shape)
# Note the previous comment about 1-d slices of matrices in the following line:
print('The (2,3) element of the product is the dot product between the 2nd row of A: \n',A[1,:],'\n and the third column of B: \n',B[:,2],'\n which is ',np.dot(A[1,:],B[:,2]))

# Try a few other elements of the product by taking inner products of appropriate slices.

u is a vector with shape  (4,)
v is a vector with shape  (4,)
The inner product of  [ 0 -2 -2  1]  and  [ 1 -2  0  1]  is  5
The inner product of 
 [[-2  0  1 -2]] 
 and 
 [[-1]
 [ 1]
 [-2]
 [-2]] 
 is  [[4]] 
 which we could also obtain using using @:  [[4]]
The product of 
 [[-1  2]
 [ 0 -2]
 [ 0  2]] 
 and 
 [[-2  2 -2  1 -3]
 [ 0 -1  2 -1 -3]] 
 is 
 [[ 2 -4  6 -3 -3]
 [ 0  2 -4  2  6]
 [ 0 -2  4 -2 -6]] 
 with shape  (3, 5)
The (2,3) element of the product is the dot product between the 2nd row of A: 
 [ 0 -2] 
 and the third column of B: 
 [-2  2] 
 which is  -4


## (b) Outer products

The outer product is the "other" way to multiply two vectors. Here you take the first vector $a$ and arrange it as a column vector (so has shape nx1). The second vector is arranged as a row vector (so has shape 1xn). The number of columns of the first vector (1) equals the number of rows of the second (1 again), so these are compatible as well. Their product has size nxn, and is called the outer product:
$$
\begin{bmatrix} a_1\\\vdots \\ a_n \end{bmatrix}
\begin{bmatrix} b_1 &\ldots & b_n\end{bmatrix}
=
\begin{bmatrix}
a_1b_1 & a_1b_2 & \ldots & a_1b_n \\
a_2b_1 & a_2 b_2 & \ldots & a_2b_n\\
\vdots & \vdots & \vdots & \vdots\\
a_nb_1 & a_n b_2 & \ldots & a_nb_n
\end{bmatrix}
$$
Verify that the multiplication above is consistent with the inner product way of multiplying the $(n,1)$ and $(1,n)$ matrices
above. Now also note that the vectors $a$ and $b$ need not have the same length for their outer product to be defined (namely,
it is perfectly ok if $a$ had length $m$ and $b$ had length $n$. Then we would multiply a $(m,1)$ matrix and a $(1,n)$ matrix,
which is valid (number of columns of the first = number of rows of the second =1). The product is then a $(m,n)$ matrix. 


###  Multiplying Matrices through the Outer Product
The second method, which is done by using the outer product, calculates $A \times B$ by multiplying columns of $A$ by rows of $B$. Thus if $A$ has shape $(m,r)$ and $B$ has shape $(r,n)$, we now think of the columns of $A$ and the rows of $B$. Namely,
we think of $A$ as  
$$
A = \begin{bmatrix} | & \ldots & | \\ {{\bf a}_1} &\ldots &{{\bf a}_r} \\ | &\ldots & | \end{bmatrix},
$$
where each ${{\bf a}_i}$ is a vector with $m$ coordinates (because $A$ has $m$ rows), and $B$ as
$$
B = \begin{bmatrix} --- {{\bf b}_1} --- \\ \vdots \\ ---{{\bf b}_r} ---\end{bmatrix},
$$
where the ${\bf b}_j$s are vectors, again each with $r$ coordinates (because $B$ has $r$ rows). Then the product of $A$ and $B$
is 
$$ 
\begin{bmatrix} | \\ {{\bf a}_1}\\ | \end{bmatrix}
\begin{bmatrix} ---{{\bf b}_1}--- \end{bmatrix} 
+ 
\ldots 
+
\begin{bmatrix} | \\ {{\bf a}_r}\\ | \end{bmatrix}
\begin{bmatrix} ---{{\bf b}_r}--- \end{bmatrix} 
$$
Of course this is consistent with the inner product way of multiplying matrices! Can you see how?

Let us do an example.
$$\begin{bmatrix} 1 & 2 \\ 3 & 4  \end{bmatrix} \times  \begin{bmatrix} 5 & 6 \\ 7 & 8  \end{bmatrix}=  
\begin{bmatrix} 1 \\ 3 \end{bmatrix}  \begin{bmatrix} 5 & 6 \end{bmatrix} +
\begin{bmatrix} 2 \\ 4 \end{bmatrix} \begin{bmatrix} 7 & 8  \end{bmatrix}
$$


In [36]:
a = npr.randint(-2,2,(1,4))
b = npr.randint(-2,2,(1,4))

# For the outer product of a and b, we must arrange a as a column and b as a row. Lucky
# for us, b is already a row. So we just need to rearrange
# a.

a.shape = (4,1)

# You can now use the @ operation, since once we arrange the vectors appropriately, 
# the outer product is just an ordinary matrix multiplication. Verify this by hand.

print('The outer product of \n',a,'\n and \n',b,'\n is \n',a@b,'\n which we could also obtain using using matmul: \n', np.matmul(a,b))

A = npr.randint(-3,3,(3,2))
B = npr.randint(-3,3,(2,5))


print('The product of \n',A,'\n and \n',B,'\n is \n',A @ B,'\n with shape ',(A @ B).shape)

# We can obtain the product of A and B using the outer product. Let us extract the columns of A
# To extract the first column. Note that we want the shape to be (3,1) (not (3,))
a1 = A[:,0].reshape(len(A[:,0]),1)
# the second:
a2 = A[:,1].reshape(len(A[:,1]),1)
# Similarly, we extract the rows of B
b1 = B[0,:].reshape(1,len(B[0,:]))
b2 = B[1,:].reshape(1,len(B[1,:]))

# The outer product way to multiply A and B:

print('AB can be obtained as \n', np.add(a1@b1, a2@b2),'\n which sure enough coincides with \n', A @ B)

The outer product of 
 [[-1]
 [ 0]
 [ 1]
 [-1]] 
 and 
 [[ 1 -1  0 -2]] 
 is 
 [[-1  1  0  2]
 [ 0  0  0  0]
 [ 1 -1  0 -2]
 [-1  1  0  2]] 
 which we could also obtain using using matmul: 
 [[-1  1  0  2]
 [ 0  0  0  0]
 [ 1 -1  0 -2]
 [-1  1  0  2]]
The product of 
 [[ 2 -1]
 [ 1  0]
 [ 0 -1]] 
 and 
 [[ 2  0  2 -3  1]
 [-1  0 -2 -3 -3]] 
 is 
 [[ 5  0  6 -3  5]
 [ 2  0  2 -3  1]
 [ 1  0  2  3  3]] 
 with shape  (3, 5)
AB can be obtained as 
 [[ 5  0  6 -3  5]
 [ 2  0  2 -3  1]
 [ 1  0  2  3  3]] 
 which sure enough coincides with 
 [[ 5  0  6 -3  5]
 [ 2  0  2 -3  1]
 [ 1  0  2  3  3]]


## <span style="color:red"> (2) Questions</span>

0. Create a new markdown cell below and type in the answers.

1. Write a function that takes in two vectors and returns their inner product. Use a loop or nditer, not inbuilt functions (we aren't aiming for a good implementation, but to ensure you understand inner products :))

2. Verify the previous function by using the numpy inbuilt command np.dot that computes the inner product. 

3. Write a function that takes in two vectors and returns their outer product. Again, use a loop or nditer, not inbuilt functions.

4. Verify the previous function by using the numpy inbuilt command np.matmul or the operator @.


In this sequence of problems, we will generate random matrices (2d arrays), and calculate the product by using by both inner and outer product methods and then compare them with the product implemented in numpy. 
 
5. Write a function in numpy that takes two arbitrary shape matrices and calculates the product by the inner product method. Use your function from part 1 to compute the inner product. Make sure it checks whether their shapes are compatible. 

6. Write a function in numpy that takes two arbitrary shape matrices and calculates the product by the outer product method. Use your function from part 3 to compute the outer product. Make sure it checks whether their shapes are compatible. 

7. Calculate the product by using the numpy operator '@' or np.matmul and verify that it equals the output from the functions written above.

8. Verify that a matrix multiplied by a column vector is simply a linear combination of the columns of the matrix. Namely, if the columns of the matrix A are a_1, a_2, .. a_n and the vector x is (x_1,... x_n), then Ax = x_1 a_1 + ... + x_n a_n. Explain why this is simply the outer product way of multiplying A and x.

9. Now verify that a row vector multiplied by a matrix is simply a linear combination of the rows of the matrix. Explain again that this is just the outer product way of multiplying.

10. Using the insights in 8: obtain a matrix P such that if A is any matrix with 3 columns, AP is a cyclic shift of the columns of A (namely the first column of A is the second column of AP, second column of A is the third column of AP, and the third column of A becomes the first column of AP).

11. Using the insight in 9: obtain P such that if A is any matrix with 3 rows, PA is a cyclic shift of the rows (cyclic as explained in 10.)



In [56]:
# 1. Write a function that takes in two vectors and returns their inner product. Use a loop or nditer, 
# not inbuilt functions (we aren't aiming for a good implementation, but to ensure you understand inner products :))


def innprod(u,v):
    def vec(z):
        # Checks if z is a vector. If yes, returns length else returns 0.        
        if isinstance(z,np.ndarray):
            if len(z.shape)==1:
                return(len(z))
            if len(z.shape)==2:
                if z.shape[0]==1 or z.shape[1]==1:
                    return(z.shape[0]*z.shape[1])
        return(0)
    
    if not (vec(u) and vec(v)):
        print('Arguments must be ndarrays!\n')
        return
    
    if not vec(u) == vec(v):
        print('Vectors must have same length!')
        return
    
    n = vec(u)
    prodl = 0
    
    # Strictly speaking, the following line isn't needed, but it
    # ensures that the loop multiplies two numbers instead of an array and a number
    u.shape = (n,)
    v.shape = (n,)
    # with a loop
    for i in range(n):
        prodl += u[i]*v[i]
        
    # with nditer
    prodn = 0
    u.shape = (1,n)
    v.shape = (1,n)
    for x in np.nditer([u,v]):
        prodn += x[0]*x[1]
    # note: because of how nditer broadcasts the arguments of u and v above, we have to
    # ensure u and v have the same shape! If not, nditer would broadcast u and v to be
    # nxn matrices, not what we want.
    return([prodl,prodn])
    
a = np.array([2,3,1,-1,4])
b = npr.randint(-2,3,5)
print('The dot product of ',a,' and ',b,' is ',innprod(a,b))
    
# 2. Verify the previous function by using the numpy inbuilt command np.dot that computes the inner product. 

# Arrange a as a row, b as a column, and take product:
a.shape = (1,5)
b.shape = (5,1)

print('numpy.dot gives the answer: ',np.dot(a,b))
print('Matrix multiplication: ', a @ b )


The dot product of  [[ 2  3  1 -1  4]]  and  [[-2  0  1  0 -1]]  is  [-7, -7]
numpy.dot gives the answer:  [[-7]]
Matrix multiplication:  [[-7]]


In [104]:
# 3. Write a function that takes in two vectors and 
# returns their outer product. Again, use a loop or nditer, not inbuilt functions.

def outprod(u,v):
    def vec(z):
        # Checks if z is a vector. If yes, returns length else returns 0.        
        if isinstance(z,np.ndarray):
            if len(z.shape)==1:
                return(len(z))
            if len(z.shape)==2:
                if z.shape[0]==1 or z.shape[1]==1:
                    return(z.shape[0]*z.shape[1])
        return(0)
    
    if not (vec(u) and vec(v)):
        print('Arguments must be ndarrays!\n')
        return
    
    # Note: we do not check if they have the same lengths---they don't have to!!!
    m = vec(u)
    n = vec(v)
    prodl = 0
    
    u.shape = (m,)
    v.shape = (n,)
    prodl = np.zeros([m,n])
    # with a loop
    for i in range(m):
        for j in range(n):
            prodl[i][j] = u[i]*v[j]
        
    # with nditer
    prodn = np.zeros([m,n])
    u.shape = (m,1)
    v.shape = (1,n)
    with np.nditer([u,v],['multi_index']) as tempobject:
        for x in tempobject: 
            i=tempobject.multi_index[0]
            j=tempobject.multi_index[1]
            prodn[i,j]= x[0]*x[1]
    # note: we are exploiting how nditer broadcasts the arguments u and v above
    return([prodl,prodn])
    
a = npr.randint(2,5,3)
b = npr.randint(-2,3,3)
print('The outer product of \n',a,'\n and \n',b,'\n is \n',outprod(a,b))
    
# 4. Verify the previous function

# Arrange a as a column, b as a row, and take product:
a.shape = (3,1)
b.shape = (1,3)

print('numpy.dot gives the answer: \n',np.dot(a,b))
print('Matrix multiplication: \n', a @ b )

The outer product of 
 [[4]
 [3]
 [4]] 
 and 
 [[ 2 -1  2]] 
 is 
 [array([[ 8., -4.,  8.],
       [ 6., -3.,  6.],
       [ 8., -4.,  8.]]), array([[ 8., -4.,  8.],
       [ 6., -3.,  6.],
       [ 8., -4.,  8.]])]
numpy.dot gives the answer: 
 [[ 8 -4  8]
 [ 6 -3  6]
 [ 8 -4  8]]
Matrix multiplication: 
 [[ 8 -4  8]
 [ 6 -3  6]
 [ 8 -4  8]]


In [107]:
# 5. Write a function in numpy that takes two arbitrary shape matrices and calculates 
# the product by the inner product method. Make sure it checks whether their shapes are compatible.  
# 6. Write a function in numpy that takes two arbitrary shape matrices and calculates the product
# by the outer product method. Make sure it checks whether their shapes are compatible. 

def matrixproduct(A,B):
    def chkmatrix(Z):
        # Checks if Z is a matrix. If yes, returns shape else returns 0.        
        if isinstance(Z,np.ndarray):
            if len(Z.shape)==2:
                return(Z.shape)
        return(0)
    
    if not (chkmatrix(A) and chkmatrix(B)):
        print('Arguments must be 2d arrays/matrices')
        return
    
    if not (A.shape[1] == B.shape[0]):
        print('Matrices cannot be multiplied')
        return
    
    r = A.shape[1]
    m = A.shape[0]
    n = B.shape[1]
    
    # Inner product approach, notice the call to the function innprod we wrote above
    prodinn = np.zeros([m,n])
    for i in range(m):
        for j in range(n):
            prodinn[i,j] = innprod(A[i,:],B[:,j])[0]            
    
    # Outer product approach, note the call to outprod we wrote above
    prodout = np.zeros([m,n])
    for l in range(r):
        prodout = np.add(prodout, outprod(A[:,l],B[l,:])[0])
    
    return(prodinn,prodout)

A = npr.randint(-3,3,[4,5])
print('A is \n',A)
B = npr.randint(-3,3,[5,2])
print('B is \n',B)

print('Their product is by the inner product method: \n')
print(matrixproduct(A,B)[0])

print('Their product is by the outer product method: \n')
print(matrixproduct(A,B)[1])

# 7. Calculate the product by using the numpy operator '@' or np.matmul and verify that it equals 
# the output from the functions written above.

print('Their product using the inbuilt @ operator: \n')
print(A @ B)

A is 
 [[-2  0  0  2 -3]
 [ 0 -2  2 -1  0]
 [ 2  1  2 -1 -3]
 [-3  1  0 -2 -3]]
B is 
 [[ 1  0]
 [-3  2]
 [ 2  0]
 [-1  2]
 [ 1  2]]
Their product is by the inner product method: 

[[-7. -2.]
 [11. -6.]
 [ 1. -6.]
 [-7. -8.]]
Their product is by the outer product method: 

[[-7. -2.]
 [11. -6.]
 [ 1. -6.]
 [-7. -8.]]
Their product using the inbuilt @ operator: 

[[-7 -2]
 [11 -6]
 [ 1 -6]
 [-7 -8]]


In [118]:
# 8. Verify that a matrix multiplied by a column vector is simply a linear combination of the columns of the matrix. 
# Namely, if the columns of the matrix A are a_1, a_2, .. a_n and the vector x is (x_1,... x_n), 
# then Ax = x_1 a_1 + ... + x_n a_n. Explain why this is simply the outer product way of multiplying A and x.

A = npr.randint(-2,3,[4,5])
x = npr.randint(-4,4,5).reshape(5,1)

print('The matrix A is \n ', A)
print('The vector x is \n',x)

print('Ax is given by: \n')
print(A @ x)

# As a linear combination of the columns:
lincomb=np.zeros([4,1])
for i in range(A.shape[1]):
    lincomb = np.add(lincomb, (A[:,i]*x[i,0]).reshape(4,1))

print('The linear combination x[0] A[:,0]+ x[1]A[:,1]+...+x[4]A[:,4] is \n')
print(lincomb)

## When you multiply Ax, the outer product approach takes the first column of A and multiplies
## it with the first row of x---but here the first row of x is simply the number in the first
## coordinate of the vector x, x_1. Simlarly the ith column of A is multiplied with the ith
## row of x, ie the number x_i. Adding it all up. the outerproduct approach to multiplying
## Ax is to add up x_1 a_1 + x_2 a_2 +... x_n a_n.


# 9. Now verify that a row vector multiplied by a matrix is simply a linear combination of the rows 
# of the matrix. Explain again that this is just the outer product way of multiplying.
# Very similar to above, if you have trouble ask me. 

The matrix A is 
  [[ 0 -2 -2  0 -2]
 [ 0  1  2  1  0]
 [-2  0  2 -1  2]
 [-2  1  2  1  1]]
The vector x is 
 [[-3]
 [-4]
 [-2]
 [-4]
 [ 3]]
Ax is given by: 

[[  6]
 [-12]
 [ 12]
 [ -3]]
The linear combination x[0] A[:,0]+ x[1]A[:,1]+...+x[4]A[:,4] is 

[[  6.]
 [-12.]
 [ 12.]
 [ -3.]]


In [126]:
#10. Using the insights in 8: obtain a matrix P such that if A is any matrix with 3 columns, 
# AP is a cyclic shift of the columns of A (namely the first column of A is the second column 
# of AP, second column of A is the third column of AP, and the third column of A becomes the first column of AP).


# The first column of the product is the third column of A. Therefore the first column of 
# P must be (0 0 1) (a column vector with entries 0, 0 and 1 in that order), since A times the
# column vector (0 0 1) = 0 times first col of A + 0 times second col of A + 1 times third col of A = third col of A.
# Second column of the product is the first column of A, so the second column of P must be (1 0 0). 
# Finally the third column of the product is the second column of P must be (0 1 0).

P = np.array([[0, 0, 1],[1, 0, 0],[0, 1, 0]]).T
print('The permutation matrix we want is \n',P)

A= npr.randint(-5,5,[9,3])
print('A is \n')
print(A)

print('AP is \n')
print(A @ P)

The permutation matrix we want is 
 [[0 1 0]
 [0 0 1]
 [1 0 0]]
A is 

[[ 0  0  0]
 [ 1  0 -4]
 [-1  1  1]
 [ 1 -4  1]
 [-2 -5  3]
 [-5  2 -2]
 [-4  1  3]
 [-2 -2 -4]
 [ 1 -5 -5]]
AP is 

[[ 0  0  0]
 [-4  1  0]
 [ 1 -1  1]
 [ 1  1 -4]
 [ 3 -2 -5]
 [-2 -5  2]
 [ 3 -4  1]
 [-4 -2 -2]
 [-5  1 -5]]


In [127]:
# very similar to prior problem.
# The first row of the product is the third row of A. Therefore the first row of 
# P must be (0 0 1) (a row vector with entries 0, 0 and 1 in that order). Second row 
# of the product is the first row of A, so the second row of P must be (1 0 0). 
# Finally the third row of the product is the second row of P must be (0 1 0).

P = np.array([[0, 0, 1],[1, 0, 0],[0, 1, 0]])
print('The permutation matrix we want is \n',P)

A= npr.randint(-5,5,[3,9])
print('A is \n')
print(A)

print('PA is \n')
print(P @ A)

The permutation matrix we want is 
 [[0 0 1]
 [1 0 0]
 [0 1 0]]
A is 

[[ 3 -2 -2  2  1  0  2 -4  1]
 [-2 -4  1  0 -2 -2  0  0  3]
 [ 2 -4 -4  0  0 -5 -1  1  4]]
PA is 

[[ 2 -4 -4  0  0 -5 -1  1  4]
 [ 3 -2 -2  2  1  0  2 -4  1]
 [-2 -4  1  0 -2 -2  0  0  3]]
