We will explore linear independence a little more. We will primarily reuse code you have developed in the prior labs, but pay attention to linearly independent vectors. Please follow up on anything you are not completely clear about from lab2/lab2a.



In [2]:
import numpy as np
import numpy.random as npr

# For plotting

import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d


Prob 1. In the cell below, create a random 8x8 matrix with each entry being 0 or 1 (call the matrix $A$). Find all pivot columns. Repeat till you get a matrix that has fewer than 8 pivots. 

In [31]:
# For lab 2-2a

# Given : Matrix, r1, r2
# Return : Swaps r1 and r2
def matrixrowswap(m,r1,r2):
    mat = m.copy()              # Shallow Copy: New structure, same references
    mat[[r1,r2]] = mat[[r2,r1]] # Row swap 
    return mat

# Given : Matrix, r1, Scalar(a)
# Return : Row1 = Row1 * a
def matrixrowmx(m,r1,a):
    mat = m.copy()              # Shallow Copy: New structure, same references
    mat[[r1]]=mat[r1,:]*a       # Row1 = Row1 * a
    return mat

# Given : matrix, r1, scalar(a), r2
# Return : Row2 = Row2 + a*Row1
def matrixrowmadd(m,r1,a,r2):
    mat = m.copy()                     # Shallow Copy: New structure, same references
    mat[[r2]]=a*mat[[r1]] + mat[[r2]]  # Row2 = Row2 + a*Row1
    return mat

# Given : Matrix, (Augmented b vector)
# Return : Reduced Row Echelon Form
def elim(m,b=None,pv=None):

    mat = m.copy()          # Shallow Copy: New structure, same references

    # For matrix of size (mxn)
    row = mat.shape[0]        # number of rows
    column = mat.shape[1]        # numer of cols 

    # p = Max Rank(Matrix)
    max_pivot = min(row,column)

    # Current Pivot and Column Counter 
    currentPivot = 0        # keeps track of current pivot
    currentColumn = 0       # keeps track of current column

    if b is not None:                         # If there is a b vector
        mat = np.concatenate((mat,b),axis=1)  # Add b onto end of Matrix Column

    if pv is not None:  
        print("\nPivot Locations:")
        pivots = []   # Creates Matrix to store pivots

    # While there are still pivots and columns to traverse through
    while (currentPivot < max_pivot) and (currentColumn < column):
        for i in range(currentPivot,row):       # for(i = 0; i < rows, i++)
            if mat[i,currentColumn] != 0.0:   # if (i,i) != 0, then a pivot

                if pv is not None:
                    pivots.append(currentColumn) # Stores pivot locations

                mat = matrixrowswap(mat,currentPivot,i)       # Swaps currentPivot with i
                temp = mat[currentPivot,currentColumn]        # Stores Pivot value in temp
                mat = matrixrowmx(mat,currentPivot,1.0/temp)  # Row1 = Row1 * 1/temp (To get 1's diagonally

                #clear out all entries above/below the pivot
                for j in range(0,row): 
                    # if current value != 0, then turn to 0. BUT, skip row with pivot
                    if (mat[j,currentColumn] != 0.0) and j != currentPivot: 
                        # Return : j = j + (-scalar)*currentPivot
                        # print(mat,currentPivot, -mat[j,currentColumn] ,j,"\n")
                        mat = matrixrowmadd(mat,currentPivot, -mat[j,currentColumn] ,j)

                # Counter
                currentPivot+=1
                currentColumn+=1
                break

            # Don't rref last column
            if i == row-1:                
                currentColumn += 1 
    if pv is not None:
        for i in range (len(pivots)-1):
            if pivots[i]+1 != pivots[i+1]:
                tempA = mat[:,pivots[i]]
                tempB = mat[:,pivots[i+1]]
                mat[:,pivots[i]] = tempB
                mat[:,pivots[i+1]] = tempA
    print("\n")
    return mat, pivots


A=npr.randint(0,2,[8,8])
print("A is :\n", A,"\n")
mat, pivots = elim(A,None,True)

print("Matrix is:\n", mat)
print("Pivots is:\n", pivots)

#A[:,0] get first column
#A[:,1] get second column
#A[:,0:2] get first two columns


A is :
 [[0 0 0 0 1 0 1 0]
 [0 1 1 0 0 0 1 1]
 [1 1 1 1 0 0 0 0]
 [0 1 0 1 1 0 0 1]
 [0 1 1 1 0 0 0 1]
 [0 1 1 1 0 0 0 1]
 [0 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0]] 


Pivot Locations:


Matrix is:
 [[ 1  0  0  0  0  0  0 -1]
 [ 0  1  0  0  0  0  0  1]
 [ 0  0  1  0  0  0  1  0]
 [ 0  0  0  1  0  0 -1  0]
 [ 0  0  0  0  1  0  1  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
Pivots is:
 [0, 1, 2, 3, 4, 5]


Prob 2. Choose 2 random vectors with size 8 each, say ${\bf w}_1$ and ${\bf w}_2$. Add the vectors $A{\bf w}_1$, $A{\bf w}_2$ to $A$ (you can stack them to the right, using np.hstack, call the resulting matrix $B$). How many pivot columns are there in $B$? Why?

In [32]:
w1=npr.randint(0,4,[8,1])
w2=npr.randint(0,4,[8,1])

B = np.hstack((A, A@w1, A@w2))
print(A, '\n')
print(B)
matrix,pivots = elim(B,None,True)
print("Matrix is:\n", matrix)
print("Pivots is:\n", pivots)
#7 pivot columns because Aw1 and Aw2 are linear combinations of A 

[[0 0 0 0 1 0 1 0]
 [0 1 1 0 0 0 1 1]
 [1 1 1 1 0 0 0 0]
 [0 1 0 1 1 0 0 1]
 [0 1 1 1 0 0 0 1]
 [0 1 1 1 0 0 0 1]
 [0 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0]] 

[[0 0 0 0 1 0 1 0 1 3]
 [0 1 1 0 0 0 1 1 7 5]
 [1 1 1 1 0 0 0 0 8 2]
 [0 1 0 1 1 0 0 1 6 5]
 [0 1 1 1 0 0 0 1 9 4]
 [0 1 1 1 0 0 0 1 9 4]
 [0 0 1 0 0 1 1 0 4 2]
 [0 0 0 0 0 0 0 0 0 0]]

Pivot Locations:


Matrix is:
 [[ 1  0  0  0  0  0  0 -1 -1 -2]
 [ 0  1  0  0  0  0  0  1  3  3]
 [ 0  0  1  0  0  0  1  0  4  2]
 [ 0  0  0  1  0  0 -1  0  2 -1]
 [ 0  0  0  0  1  0  1  0  1  3]
 [ 0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
Pivots is:
 [0, 1, 2, 3, 4, 5]


Prob 3. Generate at least 10 different permutations of the columns of $B$. In each case, find all the pivot columns. Try to identify the pivot columns in terms of their original column numbers in the matrix $B$ (before permutations).

In [37]:

for i in range (9):
    #3
    permB = np.random.permutation(B.T)
    permB = permB.T
    print("B is:\n", B)
    print("PermB is:\n", permB)
    matrix,pivots = elim(permB,None,True)
    print("Matrix is:\n", matrix)
    print("Pivots is:\n", pivots)
    print("Number of pivots:\n", len(pivots))
    #4
    q4Matrix = []
    for i in range (len(pivots)):
        q4Matrix.append(permB[:,pivots[i]].reshape(8,1))
    print("question4:\n",q4Matrix)

B is:
 [[0 0 0 0 1 0 1 0 1 3]
 [0 1 1 0 0 0 1 1 7 5]
 [1 1 1 1 0 0 0 0 8 2]
 [0 1 0 1 1 0 0 1 6 5]
 [0 1 1 1 0 0 0 1 9 4]
 [0 1 1 1 0 0 0 1 9 4]
 [0 0 1 0 0 1 1 0 4 2]
 [0 0 0 0 0 0 0 0 0 0]]
PermB is:
 [[1 1 0 0 1 3 0 0 0 0]
 [7 0 1 0 1 5 1 0 1 0]
 [8 0 0 0 0 2 1 1 1 1]
 [6 1 1 0 0 5 0 0 1 1]
 [9 0 1 0 0 4 1 0 1 1]
 [9 0 1 0 0 4 1 0 1 1]
 [4 0 0 1 1 2 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Pivot Locations:


Matrix is:
 [[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  1  1]
 [ 0  0  0  1  0  0  0 -1 -1 -1]
 [ 0  0  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  1  1]
 [ 0  0  0  0  0  0  0  0  0  0]]
Pivots is:
 [0, 1, 2, 3, 4, 5, 6]
Number of pivots:
 7
question4:
 [array([[1],
       [7],
       [8],
       [6],
       [9],
       [9],
       [4],
       [0]]), array([[1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0]]), array([[0],
       [1],
       [0],
       [1],
   

Prob 4. Write every maximal linearly independent set in the col(A) that you obtained from Prob 3.  

In [ ]:
#look at q3 

Prob 5. Repeat Prob 3 and 4 for $A^T$---ie. in $A^T$, for at least 10 different permutations of the columns of $A^T$, find all pivot **columns**. These would therefore be pivot columns of $A^T$, therefore rows of $A$. Furthermore, write every maximal linearly independent set in the row(A) that you obtained.  

In [39]:

for i in range (9):
    #3
    permB = np.random.permutation(B)
    permB = permB.T
    print("B is:\n", B)
    print("PermB is:\n", permB)
    matrix,pivots = elim(permB,None,True)
    print("Matrix is:\n", matrix)
    print("Pivots is:\n", pivots)
    print("Number of pivots:\n", len(pivots))
    #4
    q4Matrix = []
    for i in range (len(pivots)):
        q4Matrix.append(permB[:,pivots[i]].reshape(10,1))
    print("question4:\n",q4Matrix)

B is:
 [[0 0 0 0 1 0 1 0 1 3]
 [0 1 1 0 0 0 1 1 7 5]
 [1 1 1 1 0 0 0 0 8 2]
 [0 1 0 1 1 0 0 1 6 5]
 [0 1 1 1 0 0 0 1 9 4]
 [0 1 1 1 0 0 0 1 9 4]
 [0 0 1 0 0 1 1 0 4 2]
 [0 0 0 0 0 0 0 0 0 0]]
PermB is:
 [[0 0 0 0 1 0 0 0]
 [1 0 1 0 1 0 1 1]
 [1 1 1 0 1 0 0 1]
 [1 0 0 0 1 0 1 1]
 [0 0 0 0 0 1 1 0]
 [0 1 0 0 0 0 0 0]
 [0 1 1 0 0 1 0 0]
 [1 0 1 0 0 0 1 1]
 [9 4 7 0 8 1 6 9]
 [4 2 5 0 2 3 5 4]]

Pivot Locations:


Matrix is:
 [[1 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
Pivots is:
 [0, 1, 2, 4, 5, 6]
Number of pivots:
 6
question4:
 [array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [9],
       [4]]), array([[0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [4],
       [2]]), array([[0],
       [1],
       [1],
       [0],
       [0],
       [0],
  

Prob 6. Obtain the reduced row echelon forms for both $A$ and $A^T$. 

In [40]:
print("A is :\n", A,"\n")
mat, pivots = elim(A,None,True)
print("Ref is :\n", mat,"\n")
print("A.T is :\n", A.T,"\n")
mat, pivots = elim(A.T,None,True)
print("Ref is :\n", mat,"\n")

A is :
 [[0 0 0 0 1 0 1 0]
 [0 1 1 0 0 0 1 1]
 [1 1 1 1 0 0 0 0]
 [0 1 0 1 1 0 0 1]
 [0 1 1 1 0 0 0 1]
 [0 1 1 1 0 0 0 1]
 [0 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0]] 


Pivot Locations:


Ref is :
 [[ 1  0  0  0  0  0  0 -1]
 [ 0  1  0  0  0  0  0  1]
 [ 0  0  1  0  0  0  1  0]
 [ 0  0  0  1  0  0 -1  0]
 [ 0  0  0  0  1  0  1  0]
 [ 0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]] 

A.T is :
 [[0 0 1 0 0 0 0 0]
 [0 1 1 1 1 1 0 0]
 [0 1 1 0 1 1 1 0]
 [0 0 1 1 1 1 0 0]
 [1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 1 0 0 0 0 1 0]
 [0 1 0 1 1 1 0 0]] 


Pivot Locations:


Ref is :
 [[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]] 



Prob 7. Find a basis for both null$(A)$ and null$(A^T)$ using the reduced row echelon form.

In [50]:
# Function returns matrix with columns that are linearly independent and are in the nullspace of X

# X is a (m,n) matrix

# Calculate RREF of X and get pivot locations

# Calculate dimension of nullspace since equal to #rows - # pivots
# Where, Number of col = dim(null) + dim(col)

# Return None is the dimension of the nullspace is zero (Full set of pivots)

# make matrix hold basis for nullspace

# Place identity in bottom part

# Calculate dimension of F

# Place -F on top part of nullspace

# Reorder rows of nullspace matrix

def null(mat):
    rref, pivots = elim(mat,None,True)
    #mat is a mxn matrix
    m = mat.shape[0]
    n = mat.shape[1]
    dim = n - len(pivots)
    
    if dim == 0:
        print("no null space")
        return
    
    nullspace = np.zeros((n, dim))
    
    nullspace[:len(pivots), :] = -1*rref[:len(pivots), len(pivots):]
    
    nullspace[-dim:, :] = np.eye(dim)
    
    return nullspace
    
    
null(B.T)

# # Testing Matrix
# X = np.array([[1, 3, 2],
#               [2, 6, 4],
#               [0, 1, 1],
#               [0, 0, 0]])
# null(X.T)

# RREF(X) = np.array([[1, 0, -1],
#                     [0, 1, 1],
#                     [0, 0, 0],
#                     [0, 0, 0]])

# One free column -> Dim(null(X)) == 1

# NULL(X) = np.array([1],
#                    [-1],
#                    [1])

X = np.array([[1, 2, 0, 0],
                [3, 6, 1, 0],
                [2, 4, 1, 0]])

null(X)

# REFF(X.T) = np.array([[1, 2, 0, 0],
#                       [0, 0, 1, 0],
#                       [0, 0, 0, 0]])

# Two free column -> Dim(null(X.T)) == 2

# NULL(X) = np.array([-2, 0],
#                    [1, 0],
#                    [0, 0],
#                    [0 1])


Pivot Locations:



Pivot Locations:




array([[ 0.,  0.],
       [-1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.]])